command/README.md
command/test/option/duplicate_test.ts
command/test/option/negatable_test.ts
command/test/type/boolean_test.ts
command/test/type/number_test.ts
command/test/type/string_test.ts
examples/command/negatable_options.ts
flags/flags.ts
flags/test/option/collect_test.ts
flags/test/option/depends_test.ts
flags/test/option/negatable_test.ts
flags/test/type/boolean_test.ts
flags/validate_flags.ts

This PR improves the support of negatable options.
Before:
* all options with a boolean flag or an optional value were able to be called with a leading `no-` to set the option value to false.
* It was't possible to define options with a leading `no-` because of a bug.
With this PR:
* It's required to define negatable options manually.
* Add support for adding descriptions for negatable options.
Example:
```typescript
const { options } = await new Command()
// default value will be automatically set to true if no --check option exists.
// set's check to false if called.
.option("--no-check", "No check.")
.option("--color <color>", "Color name.", { default: "yellow" })
// set's color to false if called.
.option("--no-color", "No color.")
// no default value
.option("--remote <url>", "Remote …
```

feat(flags,command): improve support for negatable options

---

command/README.md
command/test/command/dotted_options_test.ts
examples/command/dotted_options.ts
examples/flags/dotted_options.ts
flags/README.md
flags/flags.ts
flags/normalize.ts
flags/test/flags/dotted_options_test.ts

This PR add's support for dotted options.
**Example:**
```typescript
import { Command } from "https://deno.land/x/cliffy/command/mod.ts";
const { options } = await new Command()
.option(
"-b.a, --bitrate.audio, --audio-bitrate <bitrate:number>",
"Audio bitrate",
)
.option(
"-b.v, --bitrate.video, --video-bitrate <bitrate:number>",
"Video bitrate",
)
.parse();
console.log(options);
```
**Output:**
```
$ deno run example.ts -b.a 300 -b.v 900
{ bitrate: { audio: 300, video: 900 } }
$ deno run example.ts --bitrate.audio 300 --bitrate.video 900
{ bitrate: { audio: 300, video: 900 } }
$ deno run example.ts --audio-bitrate 300 --video-bitrate 900
{ bitrate: { audio: 300, video: 900 } }
```

feat(flags,command): add support for dotted options

---

command/help/_help_generator.ts
command/test/command/help_command_test.ts
command/test/command/hidden_command_test.ts
command/test/integration/fixtures/help_command.out
command/test/integration/fixtures/help_command_with_argument.out
command/test/integration/fixtures/help_option_long.out
command/test/integration/fixtures/help_option_short.out
command/test/option/hidden_test.ts

fix(command): remove v prefix from version in generated help text

---

ansi/README.md

👋  Was playing around with the examples and tried out the functional example from the README, which resulted in an error:
```
❯ deno run https://deno.land/x/cliffy/examples/ansi/functional.ts
error: Uncaught PermissionDenied: Requires net access to "deno.land", run again with the --allow-net flag
at deno:core/core.js:86:46
at unwrapOpResult (deno:core/core.js:106:13)
at Object.opSync (deno:core/core.js:120:12)
at opFetch (deno:extensions/fetch/26_fetch.js:43:17)
at mainFetch (deno:extensions/fetch/26_fetch.js:170:61)
at deno:extensions/fetch/26_fetch.js:395:7
at new Promise (<anonymous>)
at fetch (deno:extensions/fetch/26_fetch.js:357:15)
at https://deno.land/x/cliffy@v0.19.2/examples/ansi/functional.ts:3:24
❯ deno --version
deno 1.11.4 (release, x86_64-apple-darwin)
v8 9.1.269.35 …
```

docs(ansi): fix functional example command

---

command/README.md
examples/command/stop_early.ts

Fix type of args in `examples/command/stop_early.ts` and the document about this.
Close #239

fix(examples): fix type of args

---

command/README.md
command/command.ts
command/help/_help_generator.ts

As per #273
Whilst making an interactive cli I found it usefull for user to be able to run --help on commands.
Without something like this the process will exit.
This change keeps all current default behaviour, and is now implemented as suggested as an option in the HelpOptions object passed to the `help()` function on a command.
Example code:
```javascript
const text = Input.prompt({message: "Server"});
Cliffy.Command()
.throwErrors()
.help({exit:false})
...
.parse(command.split(" "));
```
example of it in use:

Feature: Add option to not exit after --help (round 2)

---

command/_utils.ts
command/command.ts
command/completions/_fish_completions_generator.ts
command/completions/_zsh_completions_generator.ts
command/help/_help_generator.ts
command/test/integration/command.ts
command/test/integration/fixtures/help_command.out
command/test/integration/fixtures/help_option_long.out
command/test/integration/fixtures/help_option_short.out
command/test/integration/update_fixtures.ts

Dedent description for better multiline formatting.
```ts
new Command()
.description(
`
Foo bar baz
Foo bar baz
Foo bar baz
`
)
```
Output:
```console
Foo bar baz
Foo bar baz
Foo bar baz
```

feat(command): dedent description for better multiline support

---

CHANGELOG.md
README.md
ansi/ansi.ts
ansi/chain.ts
ansi/tty.ts
command/command.ts
command/completions/mod.ts
command/test/option/global_test.ts
command/types.ts
examples/command/global_options.ts
examples/prompt/dynamic_prompts.ts
examples/prompt/prompt_demo.ts
examples/prompt/prompt_list.ts
flags/_utils.ts
flags/flags.ts
flags/validate_flags.ts
prompt/test/prompt_list_test.ts
table/layout.ts

The method I used to make the changes in this PR:
I searched for string matches of `"'s"` in all files and reviewed each result, replacing instances with `"s"` or `"es"` as appropriate. I skipped the results which were matches for the start of string values or were correct usages (e.g. possessive/contractions, etc.). However, please review for accuracy.

fix(grammar): correct plural/possessive usage of "'s"

---

command/completions/_fish_completions_generator.ts
command/test/integration/__snapshots__/test.ts.snap

This avoids accidentally overwriting global variables with the same name.
Also changed one `[` to more idiomatic `test`.

Explicitly scope Fish variables

---

command/command.ts
examples/ansi.ts
examples/command.ts
examples/flags.ts
examples/keycode.ts
examples/keypress.ts
examples/prompt.ts
examples/table.ts

I noticed the example "command.ts" script on https://cliffy.io wasn't working.
deno run --allow-net https://deno.land/x/cliffy/examples/command.ts
```
➜  deno-cliffy git:(main) deno run --allow-net https://deno.land/x/cliffy/examples/command.ts
Check https://deno.land/x/cliffy/examples/command.ts
error: TS2345 [ERROR]: Argument of type '{ addr: string; }' is not assignable to parameter of type 'ServeInit'.
Object literal may only specify known properties, and 'addr' does not exist in type 'ServeInit'.
}, { addr: `${host}:${port}` });
~~~~~~~~~~~~~~~~~~~~~~~
at https://deno.land/x/cliffy@v0.24.3/examples/command.ts:31:10
```
I fixed the issue (replaced `{ addr: }` with `{ hostname:, port:}`) and upgraded the version of the import in the script to match the latest production version, but …

Fix examples

---

command/command.ts
command/test/command/env_var_test.ts

Test command (from #392):
```typescript
import { Command } from "./command/mod.ts";
await new Command()
.name("sample-cli")
.version("0.0.1")
.env("FOO=<value:string>", "FOO", { required: true })
.parse(Deno.args);
```
```
Usage:   sample-cli
Version: 0.0.1     
Options:
-h, --help     - Show this help.                            
-V, --version  - Show the version number for this program.  
Environment variables:
FOO  <value>  - FOO  (required)
error: Missing required environment variable "FOO".
```
Exit code: 1
```
Usage:   sample-cli
Version: 0.0.1     
Options:
-h, --help     - Show this help.                            
-V, --version  - Show the version number for this program.  
Environment variables:
FOO  <value>  - FOO  (required)
```
Exit code: 0
The default `--help` option is …

fix(command): help no longer triggers error text for missing env vars

---

command/command.ts
command/completions/complete.ts
command/test/command/arguments_test.ts
command/test/command/generic_types_test.ts
command/test/command/raw_args_test.ts
command/test/command/stop_early_test.ts
command/test/option/variadic_test.ts
examples/command/arguments_syntax_variadic.ts
examples/command/stop_early.ts
examples/command/variadic_arguments.ts

resolves #338
This is technically a breaking change, but only in the case where a command is defined with a single variadic argument.
Give this command definition:
```ts
const { args } = await new Command()
.arguments("<...myArgs>")
.parse(Deno.args);
console.log(args);
```
`args` is a nested array `[string[]]`
```sh
$ deno run ./parse_me.ts one two three
> [ [ "one", "two", "three" ] ]
```
`args` is a flat array `string[]`
```sh
$ deno run ./parse_me.ts one two three
> [ "one", "two", "three" ]
```

break(command): parse args as a flat array when arguments is defined as a single variadic variable

---

command/completions/_zsh_completions_generator.ts

Command descriptions with single quotes broke zsh completions. For an example, see https://github.com/meshcloud/unipipe-service-broker/pull/90

fix(command): escape single quotes in command description for zsh completions

---

flags/flags.ts
flags/test/option/equls_sign_test.ts

fix(flags): `equalsSign` option not working with `type` option

---

flags/flags.ts
flags/test/option/equls_sign_test.ts

fix(flags,command): value gets ignored if value of an option with an equals sign starts with a dash

---

mod.ts

fix: remove no longer existing `validateFlags` export from `cliffy/mod.ts`

---

prompt/input.ts
prompt/list.ts
prompt/secret.ts
prompt/test/input_test.ts
prompt/test/list_test.ts
prompt/test/secret_test.ts

Small grammar fix.
Messages like "Value must be longer **then** 1 but has a length of 0" should use "than" instead of "then", e.g. "Value must be longer **than** 1 but has a length of 0".

fix(prompt): grammar longer then to longer than

---

prompt/_generic_input.ts

fix(prompt): ignore special keys like F1, escape, etc. in input prompts

---

command/_utils.ts
command/command.ts
command/completions/_zsh_completions_generator.ts
command/help/_help_generator.ts
command/test/command/option_test.ts
command/test/type/custom_test.ts
examples/command/common_option_types.ts
examples/flags/flags.ts
flags/_validate_flags.ts
flags/flags.ts
flags/test/flags/dotted_options_test.ts
flags/test/option/aliases_test.ts
flags/test/option/collect_test.ts
flags/test/option/conflicts_test.ts
flags/test/option/default_test.ts
flags/test/option/depends_test.ts
flags/test/option/negatable_test.ts
flags/test/option/required_test.ts
flags/test/option/requires_test.ts
flags/test/option/standalone_test.ts
flags/test/option/unknown_test.ts
flags/test/option/value_test.ts
flags/test/option/variadic_test.ts
flags/test/type/integer_test.ts
flags/test/type/no_value_test.ts
flags/test/type/number_test.ts
flags/test/type/string_test.ts
flags/types.ts

Before:
```ts
parseFlags(Deno.args, {
flags: [{
name: "foo",
type: "boolean",
requiredValue: true,
}, {
name: "bar",
args: [{
type: "string",
optionalValue: true,
}],
}]
});
```
After:
```ts
parseFlags(Deno.args, {
flags: [{
name: "foo",
type: "boolean",
optionalValue: false,
}, {
name: "bar",
args: [{
type: "string",
optional: true,
}],
}]
});
```

breaking(flags): remove `requiredValue` option and rename `option.args[].optionalValue` to `option.args[].optional`

---

table/test/special_chars.ts
table/utils.ts

I had forgotten that it also happens with full-width characters.
fix! #330

fix: full width characters are not aligned correctly

---

command/command.ts
command/help/_help_generator.ts
command/test/command/help_test.ts

feat(command): add `indent` and `compact` option to `.help()` method

---

testing/snapshot.ts

workaround for deno bug https://github.com/denoland/deno/issues/18784

refactor(command): set default value for ignore and only in snapshotTest method

---

command/_errors.ts
command/command.ts
command/completions/_bash_completions_generator.ts
command/completions/_fish_completions_generator.ts
command/completions/_zsh_completions_generator.ts

refactor(command): throw an error if the command name is missing when generating shell completions

---

command/_errors.ts
examples/command/options.ts

refactor(command): use exit code `2` as default for validation errors

---

prompt/_generic_input.ts
prompt/_generic_list.ts
prompt/_generic_prompt.ts
prompt/_generic_suggestions.ts
prompt/_utils.ts
prompt/checkbox.ts
prompt/confirm.ts
prompt/input.ts
prompt/list.ts
prompt/number.ts
prompt/prompt.ts
prompt/secret.ts
prompt/select.ts
prompt/test/integration/__snapshots__/checkbox_value_test.ts.snap
prompt/test/integration/__snapshots__/checkbox_value_test.ts.windows.snap
prompt/test/integration/__snapshots__/prompt_test.ts.snap
prompt/test/integration/__snapshots__/prompt_test.ts.windows.snap
prompt/test/integration/checkbox_value_test.ts
prompt/test/integration/prompt_test.ts
prompt/toggle.ts

close #562
```ts
const today = new Date();
const tomorrow = new Date();
tomorrow.setDate(today.getDate() + 1);
// Select prompt:
const date = await Select.prompt({
message: "Select a date",
options: [
{ name: "Today", value: today },
{ name: "Tomorrow", value: tomorrow },
],
});
console.log("Date:", date);
// With prompt method:
const result = await prompt([{
name: "date",
type: Select<Date>,
message: "Select a date",
options: [
{ name: "Today", value: today },
{ name: "Tomorrow", value: tomorrow },
],
}]);
console.log("Date:", result.date);
```

feat(prompt): allow any type as value for select and checkbox prompt

---

table/_layout.ts
table/_utils.ts
table/cell.ts
table/consume_words.ts
table/test/ansi_regex_source_test.ts
table/test/ansi_wrapping_within_cell_test.ts

Fixes https://github.com/c4spar/deno-cliffy/issues/656
Before fix:
After fix:
3rd example "Wrapping over multiple lines" also incorporates fix for a bug that caused ANSI codes to be included in the width calculation for mid-word line wrapping.

fix(table): Wrap ANSI codes for multiline cells

---

command/completions/_zsh_completions_generator.ts
command/test/integration/__snapshots__/test.ts.snap
command/test/integration/command.ts
command/test/integration/test.ts

subCommand name with colons brakes zsh completions.
_for context see [zsh: 20 Completion System](https://zsh.sourceforge.io/Doc/Release/Completion-System.html), under `_completion`._
example code:
``` typescript
new Command()
.name("demo")
.command("completions", new CompletionsCommand())
.command("command", "description")
.command("command:test", "descriptions")
.parse(Deno.args)
```
old tab behavior -  tab output:
```
command      -- description
command      -- test:descriptions
completions  -- Generate shell completions.
```
new tab behavior -  tab output:
```
command        -- description
command:test   -- descriptions
completions    -- Generate shell completions.
```

fix(command) escape colons in subCommand name for zsh completions

---

command/command.ts

docs(command): fix markdown formatting for arguments (#677)

---

command/help/_help_generator.ts

Was alerted while building a project using cliffy:
```
https://deno.land/x/cliffy@v1.0.0-rc.3/command/help/_help_generator.ts:354:59:
354 │   return string?.charAt(0).toUpperCase() + string.slice(1) ?? "";
╵                                                            ~~
The left operand of the "??" operator here will never be null or undefined, so it will always be
returned. This usually indicates a bug in your code:
https://deno.land/x/cliffy@v1.0.0-rc.3/command/help/_help_generator.ts:354:9:
354 │   return string?.charAt(0).toUpperCase() + string.slice(1) ?? "";
╵          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
for the input `""`, the return value is already `""`. `null` and `undefined` both raise `TypeError`s.

chore(lint): Remove unused null coalescing operator

---

command/help/_help_generator.ts

fix: directly print example text w/o capitalization

---

command/upgrade/provider/npm.ts
command/upgrade/provider/npm_test.ts

feat(command): add support for npm package without scope to npm provider

---

command/upgrade/provider/npm.ts
command/upgrade/upgrade_command.ts

feat(command): add support for disabling spinner in upgrade command

---

internal/runtime/read.ts

Bun's node:process stdin implementation has multiple issues related to
raw mode, resuming, and ending it too early.
To work around this, this adds a custom branch for the read function
when running under Bun. It uses Bun's own stdin implementation to read
one chunk and then dispose the reader.
Fixes #759

fix(internal): Use Bun.stdin when using Bun to prevent process hanging

---

command/command.ts
command/upgrade/get_runtime.ts
command/upgrade/runtime/bun_runtime.ts
command/upgrade/spinner.ts
internal/runtime/delete_env.ts
internal/runtime/exit.ts
internal/runtime/get_args.ts
internal/runtime/get_columns.ts
internal/runtime/get_env.ts
internal/runtime/get_os.ts
internal/runtime/inspect.ts
internal/runtime/is_terminal.ts
internal/runtime/no_color.ts
internal/runtime/read.ts
internal/runtime/read_dir.ts
internal/runtime/read_sync.ts
internal/runtime/set_env.ts
internal/runtime/set_raw.ts
internal/runtime/stat.ts
internal/runtime/write_sync.ts
prompt/_generic_suggestions.ts

@c4spar it's impossible to combine deno-lint-ignore with dnt-shim-ignore directive so had to put deno-lint-ignore at the very top
This allows projects wrote in deno-cliffy to be made node compatible using the dnt tool

make work with dnt

---

command/command.ts
command/test/option/global_test.ts

fix(command): global options don't handle `=` correctly if passed before subcommand
