command/completions/complete.ts, command/completions/fish-completions-generator.ts, command/completions/fish.ts, command/completions/mod.ts
=> feat(command): add shell completion support for fish

prompt/_generic_list.ts, prompt/select.ts
=> fix(prompt): disabled item gets selected when it's the first option

examples/prompt/os_signals.ts, prompt/README.md, prompt/_generic_input.ts, prompt/_generic_prompt.ts
=> fix: clear stdout on ctrl+c

command/command.ts, command/test/option/action_test.ts
=> fix(command): actions on hyphenated options won't run

command/command.ts, command/test/option/action_test.ts
=> fix(command): option action not executed for options with no value

_utils/distance.ts, flags/_utils.ts, prompt/_generic_list.ts, prompt/_generic_suggestions.ts
=> Prompt: improve search

.github/workflows/lint.yml, .github/workflows/release.yml
Autopublish to nest.land and cliffy.io.
=> chore(ci): add release workflow

command/README.md, command/mod.ts, command/test/integration/command.ts, command/test/integration/fixtures/completions_complete_enum.in, command/test/integration/fixtures/completions_complete_enum.out, command/test/integration/fixtures/completions_generate_bash.out, command/test/integration/fixtures/completions_generate_fish.out, command/test/integration/fixtures/completions_generate_zsh.out, command/test/integration/fixtures/help_command.out, command/test/integration/fixtures/help_option_long.out, command/test/integration/fixtures/help_option_short.out, command/test/type/enum_test.ts, command/types/enum.ts, examples/command/enum_option_type.ts, flags/_errors.ts
=> feat(command): add enum type

command/README.md, command/command.ts, command/test/option/value_test.ts, examples/flags/value.ts, flags/README.md, flags/flags.ts, flags/test/option/value_test.ts, flags/types.ts
needs some more investigation...
=> refactor(command,flags): revert adding support for array and regexp validators and value option refactoring

table/README.md, table/cell.ts, table/layout.ts, table/row.ts, table/table.ts, table/test/align_test.ts
=> feat(table): add align option

command/upgrade/mod.ts
=> refactor(command): export github upgrade provider in upgrade/mod.ts

command/test/command/stop_early_test.ts, flags/flags.ts
=> fix(flags,command): don't normalize arguments if stopEarly is enabled

.gitignore, command/test/option/negatable_test.ts, flags/flags.ts, flags/test/option/required_test.ts
=>  fix(flags,command): required option value with default value is not required

command/README.md, command/_errors.ts, command/_utils.ts, command/command.ts, command/test/command/env_var_test.ts, command/types.ts, examples/command/environment_variables.ts
=> feat(command): add support for required env vars

command/upgrade/provider.ts, command/upgrade/upgrade_command.ts, pagic.config.tsx
close https://github.com/c4spar/deno-cliffy/issues/264
=> feat(command): support import map in upgrade command

command/README.md, command/command.ts, command/help/_help_generator.ts, command/types.ts
=> feat(command): add noExit method

command/command.ts, command/test/command/arguments_test.ts
=> fix(command): integer argument with value 0 is ignored

prompt/_generic_list.ts, prompt/_generic_prompt.ts, prompt/checkbox.ts, prompt/select.ts
=> fix(prompt): checkbox and select prompt fails with only one disabled option

dev_deps.ts, table/layout.ts, table/test/special_chars.ts, table/utils.ts
=> fix: chinese characters are not aligned correctly

prompt/_generic_prompt.ts
=> feat(prompt): add hideDefault option

prompt/_generic_list.ts, prompt/figures.ts
=> feat(prompt): add n & p keys for next & previous and left & right for next & prev page

prompt/_generic_suggestions.ts
=> fix: suggestions value is always lower cased

prompt/_generic_prompt.ts
=> fix(prompt): prompt is not rendered properly if content is longer than the terminal

flags/flags.ts, flags/test/option/default_test.ts, flags/types.ts, flags/validate_flags.ts
=> feat(flags): add `ignoreDefaults` option

command/command.ts, command/test/command/env_var_test.ts
=> fix(command): default value from option overrides env var

command/command.ts, command/test/command/allow_empty_test.ts, command/test/command/sub_command_test.ts, command/test/option/depends_test.ts, command/test/option/requires_test.ts, flags/flags.ts, flags/test/setting/allow_empty_test.ts, flags/validate_flags.ts
=> fix(command): fix allowEmpty and disable it by default

command/command.ts, command/completions/_bash_completions_generator.ts, command/completions/_fish_completions_generator.ts, command/completions/_zsh_completions_generator.ts, command/mod.ts, command/test/integration/fixtures/completions_generate_bash.out, command/test/integration/fixtures/completions_generate_fish.out, command/test/integration/fixtures/completions_generate_zsh.out, command/types/file.ts
=> feat(command): add new file type with path completion support

command/completions/_zsh_completions_generator.ts, command/test/integration/fixtures/completions_generate_zsh.out
=> fix(command): zsh completion action not called for arguments

command/command.ts, command/test/type/file_test.ts
=> fix(command): add missing default types for the FileType type

examples/command/sub_commands.ts
by the way cliffy looks really promising, was playing with yargs and cac but cliffy, so far, feels way more natural and I also love Deno isn't an afterthought 🥰
=> docs: fix typo

command/command.ts, command/test/integration/__snapshots__/test.ts.snap, command/test/integration/test.ts, command/test/integration/utils.ts
=> fix(command): error handling not working correctly

command/command.ts, command/completions/_bash_completions_generator.ts, command/test/integration/__snapshots__/test.ts.snap, prompt/number.ts, prompt/prompt.ts
I will open a new issue to fix these warnings.
=> chore(shellcheck): disable shellcheck warnings temporarily

command/command.ts, command/test/option/global_test.ts, flags/flags.ts, flags/validate_flags.ts
=> feat(command): support passing global options before sub-command

ansi/colors.ts, ansi/deps.ts, command/deps.ts, command/test/command/generic_types_test.ts, command/test/type/file_test.ts, command/upgrade/provider/deno_land.ts, deno.jsonc, dev_deps.ts, examples/ansi/custom.ts, examples/ansi/demo.ts, examples/command.ts, examples/command/examples.ts, examples/prompt/custom_prompts.ts, examples/prompt/prompt_demo.ts, examples/table/random_table_demo.ts, prompt/deps.ts, prompt/test/prompt_list_test.ts, table/deps.ts
This adds a new `update` task to automatically bump all dependencies in the project.
=> Add update task, bump dependencies

table/layout.ts, table/row.ts, table/test/span_test.ts
=> feat(table): override undefined cell values with row and col span

command/command.ts, command/test/command/generic_types_test.ts
=> fix(command): type error when trying to add a command instance with child commands

command/command.ts, command/test/option/conflicts_test.ts
=> fix(command): required options with conflicting options should be optional

ansi/ansi_escapes.ts, command/command.ts, flags/test/option/default_test.ts, flags/types.ts, flags/validate_flags.ts
=> feat(flags): add knownFlags option and deprecate ignoreDefaults

command/command.ts, command/test/integration/__snapshots__/test.ts.snap, command/test/integration/command.ts, command/test/integration/test.ts
=> fix(command): help text of main command is always shown for validation errors

command/command.ts, command/test/command/generic_types_test.ts
=> fix(command): fix type errors with typescript 4.8

command/mod.ts
Help and Completions command were exported so I believe Upgrade should be too
=> fix: Export UpgradeCommand from command module

command/command.ts, command/test/integration/__snapshots__/test.ts.snap, command/test/integration/command.ts, command/test/integration/test.ts
=> fix(command): add missing await to catch validation error correctly

command/_errors.ts, command/command.ts, command/test/command/error_handler_test.ts
=> feat(command): add cmd property to validation error

command/completions/_zsh_completions_generator.ts, command/test/integration/__snapshots__/test.ts.snap, command/test/integration/command.ts
=> fix(command): zsh completion broken for options without aliases

command/_utils.ts, command/completions/_fish_completions_generator.ts, command/test/integration/__snapshots__/test.ts.snap, command/test/integration/command.ts
=> fix(command): single quotes in option description breaks fish completions

keycode/key_code.ts, keycode/test/key_code_test.ts
fixes https://github.com/c4spar/deno-cliffy/issues/514
=> fix: unable to enter data with spaces in prompts

prompt/_generic_suggestions.ts
=> fix(prompt): suggestions only work with lowercase input

prompt/_generic_suggestions.ts
=> fix(prompt): suggestions are not completed if input is empty

table/test/special_chars.ts, table/utils.ts
Japanese characters did not work correctly either.
#330
=> fix: japanese characters are not aligned correctly

examples/table/columns.ts, table/column.ts, table/layout.ts, table/table.ts, table/test/column_test.ts
=> feat(table): implement `Column` class

command/command.ts, command/test/command/action_test.ts, dev_deps.ts
=> feat(command): add `.globalAction()` method

command/test/command/generic_types_test.ts, command/types/enum.ts
=> fix(command): enum type not always inferred correctly

prompt/_generic_prompt.ts, prompt/prompt.ts, prompt/test/integration/__snapshots__/test.ts.snap, prompt/test/integration/__snapshots__/test.ts.windows.snap
=> feat(command): add `reader` & `writer` options to `prompt()` function

dev_deps.ts, examples/prompt/prompt_list.ts, prompt/_generic_prompt.ts, prompt/prompt.ts, prompt/test/integration/__snapshots__/test.ts.snap, prompt/test/integration/__snapshots__/test.ts.windows.snap, prompt/test/integration/fixtures/prompt_list.ts, prompt/test/integration/test.ts
=> feat(prompt): refactor and export un-exported `prompt()` types and update docs

command/command.ts, command/completions/_bash_completions_generator.ts, command/completions/_fish_completions_generator.ts, command/completions/_zsh_completions_generator.ts, command/completions/bash.ts, command/completions/fish.ts, command/completions/mod.ts, command/completions/zsh.ts, command/help/_help_generator.ts, command/test/integration/__snapshots__/test.ts.snap, command/test/integration/test.ts
Allows to override the main command name.
=> feat(command): add `--name` option to completion commands

command/command.ts, command/test/command/help_command_test.ts, command/test/integration/__snapshots__/test.ts.snap
=> feat(command): show required options in help usage

command/_errors.ts, command/command.ts, command/test/command/option_test.ts, examples/command/options.ts
=> refactor(command): improve error message for duplicate option names

table/_layout.ts, table/_utils.ts, table/deps.ts, table/test/special_chars.ts
Fixes https://github.com/c4spar/deno-cliffy/issues/631
=> fix(table): More accurate cell width for Unicode chars

CONTRIBUTING.md, mod.ts
- docs: fix link to discussions
- fix: deno check
=> style: typo and type checks

prompt/checkbox.ts
=> fix(prompt): incorrect info message shown for checkbox prompt on submit

prompt/_generic_list.ts, prompt/test/integration/__snapshots__/checkbox_test.ts.snap, prompt/test/integration/__snapshots__/checkbox_test.ts.windows.snap, prompt/test/integration/__snapshots__/select_test.ts.snap, prompt/test/integration/__snapshots__/select_test.ts.windows.snap, prompt/test/integration/checkbox_test.ts, prompt/test/integration/select_test.ts
=> fix(prompt): disabled options can be selected with next page & previous page keys

command/command.ts, command/test/command/standalone_test.ts
=> fix(command): standalone option without action handler does not trigger command action

ansi/cursor_position.ts, ansi/tty.ts, prompt/_generic_prompt.ts, prompt/deps.ts
=> refactor: remove use of `Deno.isatty()`

command/completions/_zsh_completions_generator.ts, command/test/command/__snapshots__/completion_test.ts.snap, command/test/command/completion_test.ts
=> zsh completion fixes

prompt/_generic_list.ts
=> fix(prompt): fix initial page offset for checkbox and select prompt

prompt/_generic_suggestions.ts
=> fix(prompt): expand input value if file suggestions are enabled

prompt/_generic_list.ts, prompt/test/integration/__snapshots__/checkbox_group_breadcrumb_test.ts.snap, prompt/test/integration/__snapshots__/checkbox_group_breadcrumb_test.ts.windows.snap, prompt/test/integration/__snapshots__/checkbox_group_test.ts.snap, prompt/test/integration/__snapshots__/checkbox_group_test.ts.windows.snap, prompt/test/integration/__snapshots__/select_group_breadcrumb_test.ts.snap, prompt/test/integration/__snapshots__/select_group_breadcrumb_test.ts.windows.snap, prompt/test/integration/__snapshots__/select_group_test.ts.snap, prompt/test/integration/__snapshots__/select_group_test.ts.windows.snap, prompt/test/integration/checkbox_group_breadcrumb_test.ts, prompt/test/integration/checkbox_group_test.ts, prompt/test/integration/select_group_breadcrumb_test.ts, prompt/test/integration/select_group_test.ts
=> refactor(prompt): set list index to 0 instead of 1 when selecting a group option

internal/runtime/read_sync.ts
=> fix(internal): fix readSync method

examples/prompt/input.ts, prompt/input.ts
fixes #780
Couldn't write tests for it as all the tests use `.inject` which doesn't help here.
=> fix(prompt) input to fallback to default when files: true

internal/runtime/read_dir.ts, prompt/_generic_suggestions.ts
=> fix(internal): readDir check path isDirectory before Deno.readDir(path)

command/_argument_types.ts, command/test/command/generic_types_test.ts
=> fix(command): fix types for collected dotted options and wildcard options

command/upgrade/provider.ts, deno.json
=> feat(command): sort listed versions in upgrade provider

ansi/colors.ts
=> fix(ansi): add missing method bindings for setColorEnabled and getColorEnabled
